
=================================================
Ubuntu Linux Active Agent Configuration
=================================================

Purpose:
Configure Ubuntu server for Active Agent monitoring.

Modified Parameters:

Server=192.168.122.11
ServerActive=192.168.122.11
Hostname=Saby-Linux

Verification:

sudo systemctl status zabbix-agent2

zabbix_agent2 -t system.hostname

Expected Result:
Agent running and host visible in Zabbix.

Monitoring Mode:
Active Agent

Benefits:
- Agent initiates communication
- Suitable behind NAT/firewalls
